### ISSUE TITLE
multi-turn-predicate data error

### ISSUE THREAD

**Issue by love2you** [msra-nlc/MSParS#4]
I have found that all the data of type "multi-turn-predicate" have a same error.
For example, for id=38753
<question id=38753>	who design sankt annæ plads ||| how about for florida baptist building ?
<logical form id=38753>	( lambda ?x ( mso:architecture.structure.architect sankt_annæ_plads ?x ) ||| ( lambda ?x ( mso:architecture.structure.architect florida_baptist_building ?x ) )
<parameters id=38753>	sankt_annæ_plads (entity) [2,4] @Q1 ||| florida_baptist_building (entity) [3,5] @Q2
<question type id=38753>	multi-turn-predicate
The first sentence's logical form is missing one ')' at the end.
This error happens in every multi-turn-predicate data.

**Comment by nanduan** [comment]
Thank you for this question! We will check this issue immediately.

**Comment by knightmarehs** [comment]
Thanks, we have fixed this error and updated the data now.
